import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const font = Noto_Sans_JP({ subsets: ["latin"] });

import { jaJP } from "@clerk/localizations";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={jaJP}>
    <html lang="ja">
      <body className={font.className} >
        <main>{children}
        <Toaster />
        </main>
      </body>
    </html>
      </ClerkProvider>
  );
}
